---
version: 2
updates:
  # Check updates to action versions in .github/workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week on Saturday
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "gomod"
    directories:
      - "src/cloud-api-adaptor"
      - "src/cloud-api-adaptor/podvm"
      - "src/cloud-providers"
      - "src/csi-wrapper"
      - "src/peerpod-ctrl"
      - "src/webhook"
    groups:
      avast/retry-go:
        patterns:
          - github.com/avast/retry-go
      aws-sdk-go-v2:
        patterns:
          - "*aws-sdk-go-v2*"
      azure-sdk:
        patterns:
          - "github.com/Azure/azure-sdk-for-go/sdk/*"
      google-cloud:
        patterns:
          - "cloud.google.com/go/*"
      ibm-sdk:
        patterns:
          - "github.com/IBM/*"
          - "github.com/IBM-Cloud/*"
      k8s:
        patterns:
          - "*k8s.io*"
      libvirt:
        patterns:
          - "libvirt.org/go/*"
      protobuf:
        patterns:
          - "google.golang.org/protobuf"
      x/extensions:
        patterns:
          - golang.org/x/*
    schedule:
      interval: "weekly"
      day: "saturday"
