apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../yamls

images:
- name: cloud-api-adaptor
  newName: quay.io/confidential-containers/cloud-api-adaptor # change image if needed
  newTag: 6d7d2a3fe8243809b3c3a710792c8498292e2fc3

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: peer-pods-cm
  namespace: confidential-containers-system
  literals:
  - CLOUD_PROVIDER="azure"
  - AZURE_SUBSCRIPTION_ID="" #set
  - AZURE_REGION="eastus" #set
  - AZURE_INSTANCE_SIZE="Standard_D8as_v5" #set
  - AZURE_RESOURCE_GROUP="" #set

  # /subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/<AZURE_RESOURCE_GROUP>/providers/Microsoft.Network/virtualNetworks/<AZURE_VNET_NAME>/subnets/<AZURE_SUBNET_NAME>
  - AZURE_SUBNET_ID="" #set

  # /subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/<AZURE_RESOURCE_GROUP>/providers/Microsoft.Network/networkSecurityGroups/<AZURE_NSG_NAME>
  - AZURE_NSG_ID="" #set

  # /subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/<AZURE_RESOURCE_GROUP>/providers/Microsoft.Compute/images/<AZURE_IMAGE>
  - AZURE_IMAGE_ID="" #set
  - SSH_USERNAME="" #set peer pod vm admin user name
  #- DISABLECVM="" # Uncomment it if you want a generic VM
  #- PAUSE_IMAGE="" # Uncomment and set if you want to use a specific pause image
  #- VXLAN_PORT="" # Uncomment and set if you want to use a specific vxlan port. Defaults to 4789
  #- AZURE_INSTANCE_SIZES="" # comma separated
##TLS_SETTINGS
  #- CACERT_FILE="/etc/certificates/ca.crt" # for TLS
  #- CERT_FILE="/etc/certificates/client.crt" # for TLS
  #- CERT_KEY="/etc/certificates/client.key" # for TLS
  #- TLS_SKIP_VERIFY="" # for testing only
##TLS_SETTINGS

secretGenerator:
- name: auth-json-secret
  namespace: confidential-containers-system
  files:
  #- auth.json # set - path to auth.json pull credentials file
- name: peer-pods-secret
  namespace: confidential-containers-system
  # This file should look like this (w/o quotes!):
  # AZURE_CLIENT_ID=...
  # AZURE_CLIENT_SECRET=...
  # AZURE_TENANT_ID=...
  envs:
  - service-principal.env
- name: ssh-key-secret
  namespace: confidential-containers-system
  files: # key generation example: ssh-keygen -f ./id_rsa -N ""
  #- id_rsa.pub # set - path to public key
##TLS_SETTINGS
#- name: certs-for-tls
#  namespace: confidential-containers-system
#  files:
#  - <path_to_ca.crt> # set - relative path to ca.crt, located either in the same folder as the kustomization.yaml file or within a subfolder
#  - <path_to_client.crt> # set - relative path to client.crt, located either in the same folder as the kustomization.yaml file or within a subfolder
#  - <path_to_client.key> # set - relative path to client.key, located either in the same folder as the kustomization.yaml file or within a subfolder
##TLS_SETTINGS

patchesStrategicMerge:
  #- cri_runtime_endpoint.yaml # set (modify host's runtime cri socket path in the file, default is /run/containerd/containerd.sock)
##TLS_SETTINGS
  #- tls_certs_volume_mount.yaml # set (for tls)
##TLS_SETTINGS
