{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.namePrefix }}selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.namePrefix }}serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ .Values.namePrefix }}webhook-service.{{ .Release.Namespace }}.svc
  - {{ .Values.namePrefix }}webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Values.namePrefix }}selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}
