bases:
- ../../yamls
nameSuffix: -aws

images:
- name: kustomize.this/cloud-api-adaptor/image:url
  newName: quay.io/confidential-containers/cloud-api-adaptor-aws # change image if needed
  newTag: latest

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: peer-pods-cm
  namespace: confidential-containers-system
  literals:
  - CLOUD_PROVIDER="aws"
  #- PAUSE_IMAGE="" # Uncomment and set if you want to use a specific pause image
  #- VXLAN_PORT="" # Uncomment and set if you want to use a specific vxlan port. Defaults to 4789 
  #- PODVM_LAUNCHTEMPLATE_NAME="" # Uncomment and set if you want to use launch template
  # Comment out all the following variables if using launch template
  - PODVM_AMI_ID="" #set
  #- PODVM_INSTANCE_TYPE="t3.small" # caa defaults to t3.small
  #- AWS_SG_IDS="" # comma separated, if not set all SGs will be retrieved from IMDS
  #- AWS_REGION="" # if not set retrieved from IMDS
  #- SSH_KP_NAME="" # if not set retrieved from IMDS
  #- AWS_SUBNET_ID="" # if not set retrieved from IMDS

secretGenerator:
- name: auth-json-secret
  namespace: confidential-containers-system
  files:
  #- auth.json # set - path to auth.json pull credentials file
- name: peer-pods-secret
  namespace: confidential-containers-system
  literals:
  - AWS_ACCESS_KEY_ID="" # set
  - AWS_SECRET_ACCESS_KEY="" # set

patchesStrategicMerge:
  #- cri_runtime_endpoint.yaml # set (modify host's runtime cri socket path in the file, default is /run/containerd/containerd.sock)
