kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
nodes:
  - role: control-plane
    # Same image version as used for pod VM base image
    image: kindest/node:v1.34.0
    extraMounts:
      # The config.json file contains the registry secrets that you might
      # need to pull images from a private registry or docker registry to avoid
      # rate limiting.
      - hostPath: /tmp/config.json
        containerPath: /var/lib/kubelet/config.json
  - role: worker
    image: kindest/node:v1.34.0
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
      - hostPath: /var/lib/docker
        containerPath: /var/lib/docker
      # The config.json file contains the registry secrets that you might
      # need to pull images from a private registry or docker registry to avoid
      # rate limiting.
      - hostPath: /tmp/config.json
        containerPath: /var/lib/kubelet/config.json
