apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../yamls

images:
- name: cloud-api-adaptor
  newName: quay.io/confidential-containers/cloud-api-adaptor # change image if needed
  newTag: latest

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: peer-pods-cm
  namespace: confidential-containers-system
  literals:
  - CLOUD_PROVIDER="ibmcloud-powervs"
  - ENABLE_CLOUD_PROVIDER_EXTERNAL_PLUGIN="false" # flag to enable/disable dynamically load cloud provider external plugin feature
  - CLOUD_CONFIG_VERIFY="false" # It's better set as true to enable could config verify in production env
  - POWERVS_SERVICE_INSTANCE_ID="" #set
  - POWERVS_NETWORK_ID="" #set
  - POWERVS_SSH_KEY_NAME="" #set
  - POWERVS_IMAGE_ID="" #set
  - POWERVS_ZONE="" #set
  - CRI_RUNTIME_ENDPOINT="/run/cri-runtime/containerd.sock"
  #- CA_PUBLIC_KEY_PATH="" # Uncomment and set the path of the CA public key 
  #- POWERVS_MEMORY="" # Uncomment and set if you want to use a specific amount of memory
  #- POWERVS_PROCESSORS="" # Uncomment and set if you want to use a specific number of CPUs
  #- POWERVS_PROCESSOR_TYPE="" # Uncomment and set if you want to use a specific processor type
  #- POWERVS_SYSTEM_TYPE="" # Uncomment and set if you want to use a specific system type
  #- PAUSE_IMAGE="" # Uncomment and set if you want to use a specific pause image
  #- TUNNEL_TYPE="" # Uncomment and set if you want to use a specific tunnel type. Defaults to vxlan
  #- VXLAN_PORT="" # Uncomment and set if you want to use a specific vxlan port. Defaults to 4789
  #- PROXY_TIMEOUT="" # Uncomment and set if you want to pass a specific timeout. Defaults to 5m
  #- USE_PUBLIC_IP="true" # Uncomment if you want to use public ip for podvm
  #- ENABLE_SFTP="true" # Uncomment if you want to send user-data via SFTP
  #- CLOUD_USER_NAME="" # Uncomment and set the cloud user name
  #- FORWARDER_PORT="" # Uncomment and set if you want to use a specific port for agent-protocol-forwarder. Defaults to 15150
  #- PEERPODS_LIMIT_PER_NODE="10" # Max number of peer pods that can be created per node. Default is 10
  #- REMOTE_HYPERVISOR_ENDPOINT="/run/peerpod/hypervisor.sock" # Path to Kata remote hypervisor socket. Default is /run/peerpod/hypervisor.sock
  #- PEER_PODS_DIR="/run/peerpod/pods" # Path to peer pods directory. Default is /run/peerpod/pods
##TLS_SETTINGS
  #- CACERT_FILE="/etc/certificates/ca.crt" # for TLS
  #- CERT_FILE="/etc/certificates/client.crt" # for TLS
  #- CERT_KEY="/etc/certificates/client.key" # for TLS
  #- TLS_SKIP_VERIFY="" # for testing only
##TLS_SETTINGS

secretGenerator:
- name: peer-pods-secret
  namespace: confidential-containers-system
  # the below file should be in this format
  # $ cat cloud-credentials.env
  # IBMCLOUD_API_KEY=...
  envs:
  - cloud-credentials.env

# - name: peer-pods-ca-key
#   namespace: confidential-containers-system
#   files:
#   - <path_to_ca.pub>

##TLS_SETTINGS
#- name: certs-for-tls
#  namespace: confidential-containers-system
#  files:
#  - <path_to_ca.crt> # set - relative path to ca.crt, located either in the same folder as the kustomization.yaml file or within a subfolder
#  - <path_to_client.crt> # set - relative path to client.crt, located either in the same folder as the kustomization.yaml file or within a subfolder
#  - <path_to_client.key> # set - relative path to client.key, located either in the same folder as the kustomization.yaml file or within a subfolder
##TLS_SETTINGS

patchesStrategicMerge:
##TLS_SETTINGS
  #- tls_certs_volume_mount.yaml # set (for tls)
##TLS_SETTINGS
  #- ca_public_key_volume_mount.yaml # set for ENABLE_SFTP=true
