apiVersion: v2
name: peerpodctrl
description: Controller for cleaning up dangling peer pod cloud resources
type: application
version: 0.1.0
appVersion: "v0.17.0"

keywords:
  - confidential-containers
  - peerpods
  - controller

home: https://github.com/confidential-containers/cloud-api-adaptor

sources:
  - https://github.com/confidential-containers/cloud-api-adaptor

maintainers:
  - name: Confidential Containers Community
    url: https://github.com/confidential-containers
