apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../yamls

images:
- name: cloud-api-adaptor
  newName: quay.io/confidential-containers/cloud-api-adaptor # change image if needed
  newTag: e205a788d6d3ad619bd8b0896c6a847b05c0f745

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: peer-pods-cm
  namespace: confidential-containers-system
  literals:
  - CLOUD_PROVIDER="aws"
  - ENABLE_CLOUD_PROVIDER_EXTERNAL_PLUGIN="false" # flag to enable/disable dynamically load cloud provider external plugin feature
  - CLOUD_CONFIG_VERIFY="false" # It's better set as true to enable could config verify in production env
  #- DISABLECVM="true" # Uncomment it if you want a generic VM
  #- PAUSE_IMAGE="" # Uncomment and set if you want to use a specific pause image
  #- TUNNEL_TYPE="" # Uncomment and set if you want to use a specific tunnel type. Defaults to vxlan
  #- VXLAN_PORT="" # Uncomment and set if you want to use a specific vxlan port. Defaults to 4789
  #- PODVM_LAUNCHTEMPLATE_NAME="" # Uncomment and set if you want to use launch template
  # Comment out all the following variables if using launch template
  - PODVM_AMI_ID="" #set
  #- PODVM_INSTANCE_TYPE="m6a.large" # caa defaults to m6a.large
  #- PODVM_INSTANCE_TYPES="" # comma separated
  #- AWS_SG_IDS="" # comma separated, if not set all SGs will be retrieved from IMDS
  #- AWS_REGION="" # if not set retrieved from IMDS
  #- SSH_KP_NAME="" # if not set retrieved from IMDS
  #- AWS_SUBNET_ID="" # if not set retrieved from IMDS
  #- TAGS="" # Uncomment and add key1=value1,key2=value2 etc if you want to use specific tags for podvm
  #- USE_PUBLIC_IP="true" # Uncomment if you want to use public ip for podvm
  #- EXTERNAL_NETWORK_VIA_PODVM="true" # Uncomment if you want to use podvm as external network
  #- POD_SUBNET_CIDRS="10.244.0.0/16,10.96.0.0/12" # Uncomment and set if you want to use specific subnet cidrs for podvm. Comma separated. The default is for a kind cluster
  #- ROOT_VOLUME_SIZE="30" # Uncomment and set if you want to use a specific root volume size. Defaults to 30
  #- FORWARDER_PORT="" # Uncomment and set if you want to use a specific port for agent-protocol-forwarder. Defaults to 15150
  #- PEERPODS_LIMIT_PER_NODE="10" # Max number of peer pods that can be created per node. Default is 10
  #- REMOTE_HYPERVISOR_ENDPOINT="/run/peerpod/hypervisor.sock" # Path to Kata remote hypervisor socket. Default is /run/peerpod/hypervisor.sock
  #- PEER_PODS_DIR="/run/peerpod/pods" # Path to peer pods directory. Default is /run/peerpod/pods
  #- ENABLE_SCRATCH_SPACE="false"  # Enable scratch space for pod VMs. Default is false
##TLS_SETTINGS
  #- CACERT_FILE="/etc/certificates/ca.crt" # for TLS
  #- CERT_FILE="/etc/certificates/client.crt" # for TLS
  #- CERT_KEY="/etc/certificates/client.key" # for TLS
  #- TLS_SKIP_VERIFY="" # for testing only
##TLS_SETTINGS

secretGenerator:
- name: peer-pods-secret
  namespace: confidential-containers-system
  # This file should look like this (w/o quotes!):
  # AWS_ACCESS_KEY_ID=...
  # AWS_SECRET_ACCESS_KEY=...
  # AWS_SESSION_TOKEN=... (optional, for temporary credentials)
  envs:
    - aws-cred.env
##TLS_SETTINGS
#- name: certs-for-tls
#  namespace: confidential-containers-system
#  files:
#  - <path_to_ca.crt> # set - relative path to ca.crt, located either in the same folder as the kustomization.yaml file or within a subfolder
#  - <path_to_client.crt> # set - relative path to client.crt, located either in the same folder as the kustomization.yaml file or within a subfolder
#  - <path_to_client.key> # set - relative path to client.key, located either in the same folder as the kustomization.yaml file or within a subfolder
##TLS_SETTINGS

patchesStrategicMerge:
##TLS_SETTINGS
  #- tls_certs_volume_mount.yaml # set (for tls)
##TLS_SETTINGS
