apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../yamls

images:
- name: cloud-api-adaptor
  newName: 192.168.122.1:5000/cloud-api-adaptor # change image if needed
  newTag: e205a788d6d3ad619bd8b0896c6a847b05c0f745

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: peer-pods-cm
  namespace: confidential-containers-system
  literals:
  - CLOUD_PROVIDER="gcp"
  - PODVM_IMAGE_NAME="" # set from step "Build Pod VM Image" in gcp/README.md
  - GCP_PROJECT_ID="" # set
  - GCP_ZONE="" # set e.g. "us-west1-a"
  - GCP_MACHINE_TYPE="e2-medium" # replace if needed. caa defaults to e2-medium
  - GCP_NETWORK="global/networks/default" # replace if needed.
  - GCP_CONFIDENTIAL_TYPE="" # Needs to be set when DisableCVM=false. i.e: TDX or SEV_SNP. Check if the machine type is compatible.
  #- DISABLECVM="true" # Uncomment it if you want a generic VM
  #- PEERPODS_LIMIT_PER_NODE="10" # Max number of peer pods that can be created per node. Default is 10
  #- REMOTE_HYPERVISOR_ENDPOINT="/run/peerpod/hypervisor.sock" # Path to Kata remote hypervisor socket. Default is /run/peerpod/hypervisor.sock
  #- PEER_PODS_DIR="/run/peerpod/pods" # Path to peer pods directory. Default is /run/peerpod/pods
  #- PAUSE_IMAGE="" # Uncomment and set if you want to use a specific pause image
  #- ROOT_VOLUME_SIZE="10" # Uncomment and set if you want to use a specific root volume size. Defaults to 10
  #- TUNNEL_TYPE="" # Uncomment and set if you want to use a specific tunnel type. Defaults to vxlan
  #- VXLAN_PORT="" # Uncomment and set if you want to use a specific vxlan port. Defaults to 4789
  #- TAGS="" # Uncomment and add key1=value1,key2=value2 etc if you want to use specific tags for podvm. Tags must already exist in the GCP project
  #- ENABLE_SCRATCH_SPACE="false"  # Enable scratch space for pod VMs. Default is false
##TLS_SETTINGS
  #- CACERT_FILE="/etc/certificates/ca.crt" # for TLS
  #- CERT_FILE="/etc/certificates/client.crt" # for TLS
  #- CERT_KEY="/etc/certificates/client.key" # for TLS
  #- TLS_SKIP_VERIFY="" # for testing only
##TLS_SETTINGS

secretGenerator:
- name: peer-pods-secret
  namespace: confidential-containers-system
  files:
  #- GCP_CREDENTIALS # make sure this file has the application credentials. You can reuse the Packer creds created in "Build Pod VM Image"
##TLS_SETTINGS
#- name: certs-for-tls
#  namespace: confidential-containers-system
#  files:
#  - <path_to_ca.crt> # set - path to ca.crt
#  - <path_to_client.crt> # set - path to client.crt
#  - <path_to_client.key> # set - path to client.key
##TLS_SETTINGS

patchesStrategicMerge:
##TLS_SETTINGS
  #- tls_certs_volume_mount.yaml # set (for tls)
##TLS_SETTINGS
