# Copyright Confidential Containers Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Run tests for peer-pod controller.
---
name: controller

on:
  pull_request:
  workflow_dispatch:

jobs:
  controller_job:
    name: peerpodconfig-ctrl
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: peerpodconfig-ctrl
    strategy:
      matrix:
        go_version:
          - "1.20.6"
    steps:
      - name: Checkout the pull request code
        uses: actions/checkout@v3
      - name: Setup Golang version ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - name: Verify go modules
        run: make verify-modules
      - name: Verify go generated code
        run: make verify-gen
      - name: Build the controller manager
        run: make build
      - name: Run unit tests
        run: make test
      - name: Build the controller image
        run: make docker-build
