# Copyright Confidential Containers Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Build and push the project release images.
---
name: Release project images
on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  caa:
    uses: ./.github/workflows/caa_build_and_push_per_arch.yaml
    with:
      dev_tags: ${{ github.event.release.tag_name }}-dev
      release_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit

  csi-wrapper:
    uses: ./.github/workflows/csi_wrapper_images.yaml
    with:
      image_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit

  peerpod-ctrl:
    uses: ./.github/workflows/peerpod-ctrl_image.yaml
    with:
      image_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit

  podvm_builder:
    uses: ./.github/workflows/podvm_builder.yaml
    with:
      image_tag: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit

  podvm_binaries:
    needs: [podvm_builder]
    uses: ./.github/workflows/podvm_binaries.yaml
    with:
      image_tag: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit

  podvm:
    needs: [podvm_binaries]
    uses: ./.github/workflows/podvm.yaml
    with:
      image_tag: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit

  podvm-mkosi:
    uses: ./.github/workflows/podvm_mkosi.yaml
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, s390x]
    with:
      image_tag: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
      arch: ${{ matrix.arch}}
      debug: false
    secrets: inherit

  webhook:
    uses: ./.github/workflows/webhook_image.yaml
    with:
      image_tags: ${{ github.event.release.tag_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit
