name: Create Test Images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'src/cloud-api-adaptor/test/e2e/fixtures/Dockerfile.*'
      - '.github/workflows/test-images.yaml'

defaults:
  run:
    working-directory: src/cloud-api-adaptor

permissions: {}

jobs:
  list-dockerfiles:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ env.MATRIX }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - id: set-matrix
        run: echo "MATRIX=$(find test/e2e/fixtures/Dockerfile.* | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_ENV"
  build:
    name: Create Test Images
    needs: list-dockerfiles
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        targets: ${{ fromJson(needs.list-dockerfiles.outputs.matrix) }}
        arch: [amd64, s390x]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

    - name: Login to Quay container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      with:
        registry: quay.io
        username: ${{ vars.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: determine docker tag by splitting branch name on slash
      id: docker-tag
      shell: bash
      run: |
        file_name=$(basename "${{matrix.targets}}")
        echo "DOCKER_TAG=${file_name##*.}" >> "$GITHUB_ENV"
    - name: Build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        tags: |
          quay.io/confidential-containers/test-images:${{env.DOCKER_TAG}}
        push: true
        context: src/cloud-api-adaptor/
        platforms: linux/s390x,linux/amd64
        file: src/cloud-api-adaptor/${{matrix.targets}}
        build-args: |
          "ARCH=${{ matrix.arch }}"
